# Generated by Django 4.2.29 on 2026-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
